# Generated by Django 3.0.7 on 2020-09-03 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='perchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Repo.Perchase'),
        ),
    ]
