# Generated by Django 3.1.1 on 2020-09-03 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Repo', '0002_auto_20200903_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Dep_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
